name: GitHub PR Lint

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  semantic-pr:
    name: Validate semantic PR title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Semantic PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
