name: Release
on:
  push:
    branches:
      - "*.x"

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          title: 🚀 Release new version
          publish: npx @changesets/cli tag # this will create a new tag and a new release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}